steps:
# First, install dependencies for the functions
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'functions'

# Then, deploy the function
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'functions'
    - 'deploy'
    - 'getAiTaxAdvice'
    - '--source=./functions'
    - '--trigger-http'
    - '--runtime=nodejs20'
    - '--region=us-central1'
    - '--entry-point=getAiTaxAdvice'
    - '--allow-unauthenticated'
    - '--set-secrets=GEMINI_API_KEY=GEMINI_API_KEY:latest'

# Add this new section to solve the error
options:
  logging: CLOUD_LOGGING_ONLY